# here i tell docker which version docker-compose we coding (writing)
version: '3.8'

# here i describe services e.g. here im going to list containers that i want to build
# each service, actually describe a docker run command
services:
  
  # docker run --name weezer-db -d -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=weezer -e MYSQL_TCP_PORT=3306 -p 3308:3306 idoyahav/weezer-db:1.0.0
  database:
    container_name: weezer-db-compose
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=weezer
      - MYSQL_TCP_PORT=3306
    ports:
      - "3309:3306"
    # image: idoyahav/weezer-db:1.0.0     <--   pull (download) existing image from Docker Hub
    build: ./database                   #   <-- build the image from database directory
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]     # <-- Docker runs this inside the container to check if MySQL is responsive
      interval: 1m30s                                           # <-- how often to run the healthcheck (every 1.5 minutes)
      timeout: 30s                                             # <-- how long to wait for a response before marking it as "unhealthy"
      retries: 5                                               # <-- how many times to retry before declaring the container as "unhealthy"
      start_period: 30s                                        # <-- grace period before starting health checks (gives MySQL time to start)

  # docker run --name weezer-backend -d -e NODE_ENV=docker  -p 3010:3000 idoyahav/weezer-backend:4.0.0
  backend:
    container_name: weezer-backend-compose
    environment:
      - NODE_ENV=compose
    ports:
      - "3020:3000"
    build: ./backend
    depends_on:
      database: 
        condition: service_healthy       # <-- here I wait until the database passes its healthcheck and is ready to accept connections

# docker run --name weezer-frontend -d -p 3011:5173 idoyahav/weezer-frontend:1.0.1
  frontend:
    container_name: weezer-frontend-compose
    ports:
      - 3012:80                        # <-- mapping Nginx's internal port 80 to 3011 on the host, so the frontend is accessible from outside the container
    build: 
      context: ./frontend
      dockerfile: Dockerfile.compose

# docker run --name localstack -d --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
  localstack: 
    container_name: weezer-localstack
    ports: 
      - 4566:4566
      - 4510-4559:4510-4559
    image: localstack/localstack